import numpy as np
import pytest
from scipy.ndimage import gaussian_filter

from flyguard.optical_flow import (
    flow_sequence,
    lucas_kanade_flow,
    lucas_kanade_flow_iterative,
    lucas_kanade_flow_pyramidal,
    to_grayscale,
)


def _textured_pair(dx, dy, seed=0, size=64, pad=10):
    """A smooth random-textured image pair with a known integer pixel
    shift (dx right, dy down) between them, generated by sampling a larger
    canvas at two offset windows -- exact ground truth, no interpolation
    error, and enough texture for LK's gradient-based solve to be
    well-conditioned everywhere."""
    rng = np.random.default_rng(seed)
    base = gaussian_filter(rng.random((size + 2 * pad, size + 2 * pad)), sigma=2.0)
    img1 = base[pad:pad + size, pad:pad + size]
    img2 = base[pad - dy:pad - dy + size, pad - dx:pad - dx + size]
    return img1, img2


INTERIOR = (slice(15, 49), slice(15, 49))  # avoid border/window-edge effects


def test_to_grayscale_shape_and_range():
    frame = np.random.default_rng(0).integers(0, 256, size=(8, 8, 3), dtype=np.uint8)
    gray = to_grayscale(frame)
    assert gray.shape == (8, 8)
    assert gray.min() >= 0.0 and gray.max() <= 1.0


def test_lucas_kanade_flow_direction_correct_for_small_shifts():
    img1, img2 = _textured_pair(dx=1, dy=-1)
    vx, vy = lucas_kanade_flow(img1, img2, window=15)
    assert vx[INTERIOR].mean() > 0.5
    assert vy[INTERIOR].mean() < -0.5


def test_lucas_kanade_flow_underestimates_larger_shifts():
    """Documents the known single-pass LK bias this project found and
    fixed with the iterative version -- regression test for the finding,
    not just a correctness check."""
    img1, img2 = _textured_pair(dx=2, dy=0)
    vx, vy = lucas_kanade_flow(img1, img2, window=15)
    est = vx[INTERIOR].mean()
    assert 1.0 < est < 1.95, f"expected a noticeable underestimate of true=2, got {est:.2f}"


@pytest.mark.parametrize("dx,dy", [(2, 0), (0, 2), (2, 2), (-1, 3), (1, -1), (4, 0)])
def test_lucas_kanade_flow_iterative_recovers_ground_truth(dx, dy):
    img1, img2 = _textured_pair(dx=dx, dy=dy)
    vx, vy = lucas_kanade_flow_iterative(img1, img2, window=15, n_iters=4)
    est_vx, est_vy = np.median(vx[INTERIOR]), np.median(vy[INTERIOR])
    assert abs(est_vx - dx) < 0.15, f"vx: true={dx} est={est_vx:.2f}"
    assert abs(est_vy - dy) < 0.15, f"vy: true={dy} est={est_vy:.2f}"


def test_lucas_kanade_flow_is_zero_for_identical_frames():
    img1, _ = _textured_pair(dx=0, dy=0)
    vx, vy = lucas_kanade_flow(img1, img1.copy(), window=15)
    np.testing.assert_allclose(vx, 0.0, atol=1e-9)
    np.testing.assert_allclose(vy, 0.0, atol=1e-9)


def test_lucas_kanade_flow_rejects_mismatched_shapes():
    a = np.zeros((10, 10))
    b = np.zeros((10, 12))
    with pytest.raises(ValueError):
        lucas_kanade_flow(a, b)


def test_flow_sequence_shape_matches_n_frames_minus_one():
    rng = np.random.default_rng(0)
    frames = rng.integers(0, 256, size=(5, 32, 32, 3), dtype=np.uint8)
    vx, vy = flow_sequence(frames, window=9)
    assert vx.shape == (4, 32, 32)
    assert vy.shape == (4, 32, 32)


# --- pyramidal (coarse-to-fine) -------------------------------------------

# Large shifts need a bigger canvas and margin than the default helper uses,
# and a wider interior crop to stay clear of window-edge effects.
BIG = dict(size=128, pad=24)
BIG_INTERIOR = (slice(35, 93), slice(35, 93))


# Tolerance loosens at the top of the range: with a 128 px image and a 13 px
# window the pyramid bottoms out around 16 px, so an 11.4 px displacement is
# near the limit of what the coarsest level can resolve (measured residual
# ~0.4 px, against ~12 px for warp-and-resolve alone).
@pytest.mark.parametrize("dx,dy,tol", [(6, 0, 0.1), (8, -4, 0.1), (11, 3, 0.5)])
def test_pyramidal_recovers_shifts_that_defeat_plain_warping(dx, dy, tol):
    """Large displacements are exactly where warp-and-resolve alone fails,
    and it fails by collapsing toward zero rather than saturating -- which is
    what inverted the sign of the wall-avoidance signal in `flyguard.avoid`
    (a wall close enough to scrape read as emptier than open corridor)."""
    img1, img2 = _textured_pair(dx, dy, **BIG)
    vx_i, vy_i = lucas_kanade_flow_iterative(img1, img2, window=13, n_iters=3)
    vx_p, vy_p = lucas_kanade_flow_pyramidal(img1, img2, window=13, n_iters=3, n_levels=4)

    err_iter = np.hypot(vx_i[BIG_INTERIOR].mean() - dx, vy_i[BIG_INTERIOR].mean() - dy)
    err_pyr = np.hypot(vx_p[BIG_INTERIOR].mean() - dx, vy_p[BIG_INTERIOR].mean() - dy)
    assert err_pyr < tol
    assert err_pyr < 0.2 * err_iter


def test_plain_warping_collapses_toward_zero_on_large_shifts():
    """Pins the failure *mode*, not just that it is inaccurate: the estimate
    goes to ~0, so a fast-moving surface reads as a stationary one."""
    img1, img2 = _textured_pair(11, 0, **BIG)
    vx, _ = lucas_kanade_flow_iterative(img1, img2, window=13, n_iters=3)
    assert abs(vx[BIG_INTERIOR].mean()) < 2.0


@pytest.mark.parametrize("dx,dy", [(1, 0), (2, 0), (2, 2)])
def test_pyramidal_is_still_accurate_on_small_shifts(dx, dy):
    """Adding levels must not cost accuracy in the range that already worked."""
    img1, img2 = _textured_pair(dx, dy, **BIG)
    vx, vy = lucas_kanade_flow_pyramidal(img1, img2, window=13, n_iters=3, n_levels=3)
    assert np.hypot(vx[BIG_INTERIOR].mean() - dx, vy[BIG_INTERIOR].mean() - dy) < 0.15


def test_pyramidal_is_zero_for_identical_frames():
    img1, _ = _textured_pair(0, 0, **BIG)
    vx, vy = lucas_kanade_flow_pyramidal(img1, img1, window=13, n_iters=3)
    np.testing.assert_allclose(vx, 0.0, atol=1e-9)
    np.testing.assert_allclose(vy, 0.0, atol=1e-9)


def test_pyramidal_stops_adding_levels_when_the_window_outgrows_the_image():
    """A window wider than the image measures nothing; asking for more levels
    than the image supports must degrade gracefully, not crash."""
    img1, img2 = _textured_pair(1, 0, size=64, pad=10)
    vx, vy = lucas_kanade_flow_pyramidal(img1, img2, window=21, n_iters=2, n_levels=8)
    assert vx.shape == img1.shape
    assert np.all(np.isfinite(vx)) and np.all(np.isfinite(vy))
